############################################################################3
#
# SC Configuration
#

- name: Check Storage Controllers are listening
  wait_for: host="{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}" port=8773 state=started
  with_items: "{{ groups.sc }}"
  tags:
  - sc_config

- name: Check SC is not set according to logs
  wait_for: path="{{ eucalyptus_cloudoutput_path }}" search_regex="das,overlay"
  tags:
  - sc_config

- name: Configure SC block manager
  shell: source "{{ euca_admin_creds_path }}"/eucarc ; euca-modify-property -p "{{ item['partition'] }}".storage.blockstoragemanager="{{ item['mode'] }}"
  with_items: "{{ sc_clusters }}"
  tags:
  - sc_config
  ignore_errors: yes

- name: Wait for SC to be ENABLED
  pause: prompt="Making sure SC is now ENABLED" seconds=15

- name: Configure the block manager properties
  shell: source "{{ euca_admin_creds_path }}"/eucarc ; euca-modify-property -p "{{ item.0['partition'] }}".storage."{{ item.1['name'] }}"="{{ item.1['value'] }}"
  with_subelements:
  - "{{ sc_clusters }}"
  - properties
  tags:
  - sc_config
  ignore_errors: yes
