#
# Create briges on NCs
#

- name: Get IP
  shell: echo {{ vlan_ip }} | cut -d '/' -f 1
  register: ip
  tags:
  - network_config
  when:
  - use_vlans

- name: Get prefix
  shell: echo {{ vlan_ip }} | cut -d '/' -f 2
  register: prefix
  tags:
  - network_config
  when:
  - use_vlans

- name: Update the bridged interface config file
  template: src=iface.j2 dest="{{ netcfg_path }}/ifcfg-{{ hostvars[inventory_hostname]['vnet_private'] }}"
  tags:
  - network_config
  when:
  - not use_vlans

- name: Creates the Bridge config file | VLAN
  template: src=bridge.j2 dest="{{ netcfg_path }}/ifcfg-{{ bridge_prefix }}{{ vlan_tag }}"
  tags:
  - network_config
  when:
  - use_vlans

- name: Creates the Bridge config file | NOVLAN
  template: src=bridge.j2 dest="{{ netcfg_path }}/ifcfg-{{ bridge_prefix }}{{ bridge_id }}"
  tags:
  - network_config
  when:
  - not use_vlans

- name: Network restart
  service: name=network state=restarted
  tags:
  - network_config
