#
# CLC config
#

- name: Setup CLC
  yum: name={{ item }} state=present
  with_items:
  - eucalyptus-cloud
  - eucalyptus-imaging-worker-image
  - eucalyptus-load-balancer-image

- name: CLC Java binding
  lineinfile: regexp=CLOUD_OPTS line=CLOUD_OPTS\=\"--bind-addr={{  hostvars[inventory_hostname]['ansible_' + java_iface]['ipv4']['address'] }}\" dest={{ euca_conf_path }}

- name: Check if Eucalyptus has been initialized
  stat: path={{ euca_db_path }}
  register: db_stat

- name: Initialize Eucalyptus CLC
  shell: euca_conf --initialize
  when: db_stat.stat.exists == False

- name: Start Eucalyptus
  service: name=eucalyptus-cloud state=started

- name: Generate ssh-key on CLC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: clc_public_key

- name: Deploy CLC public_key
  authorized_key: user=root state=present key="{{ clc_public_key.ssh_public_key }}"

- name: Config CLC ssh config
  copy: src=ssh_config dest=/root/.ssh/config

- name: Getting CLC public key
  fetch: src=/root/.ssh/id_rsa.pub dest=/var/tmp/clc-pub-key flat=yes

- name: create the EDGE config
  template: src=network.json.j2 dest=/root/network.json
