#
# CLC config
#

- name: Setup CLC
  yum: name={{ item }} state=present
  with_items:
  - eucalyptus-cloud
  - eucalyptus-imaging-worker-image
  - eucalyptus-load-balancer-image

- name: CLC JAVA Binding
  template: src=eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
  tags:
  - clc
  - init_config

- name: Check if Eucalyptus has been initialized
  stat: path={{ euca_db_path }}
  register: db_stat
  tags:
  - init_cloud
  - clc

- name: Initialize Eucalyptus CLC
  shell: euca_conf --initialize
  when: db_stat.stat.exists == False
  tags:
  - clc
  - init_config

- name: Start Eucalyptus
  service: name=eucalyptus-cloud state=started
  tags:
  - services
  - euca_cloud

- name: Generate ssh-key on CLC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: clc_public_key
  tags:
  - clc
  - config

- name: Deploy CLC public_key
  authorized_key: user=root state=present key="{{ clc_public_key.ssh_public_key }}"
  tags:
  - clc
  - config

- name: Config CLC ssh config
  copy: src=ssh_config dest=/root/.ssh/config
  tags:
  - clc
  - config

- name: Getting CLC public key
  fetch: src=/root/.ssh/id_rsa.pub dest=/var/tmp/clc-pub-key flat=yes
  tags:
  - clc
  - config

- name: create the EDGE config
  template: src=network.json.j2 dest=/root/network.json
  tags:
  - clc
  - cloud_config
