#
# Deploy
#

- hosts: nc

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerNC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - startCompute
