#
# Deploy
#

- hosts: all

- hosts: all
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - setup
  - networking

- hosts: all

- hosts: all
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - common

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - clc

- hosts: ufs
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - ufs

- hosts: walrus
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - walrus

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerUFS
  - registerWalrus

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - cc

- hosts: sc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - sc

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerCC
  - registerSC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - nc

- hosts: nc

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerNC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - startCompute

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/osg.yml
  - vars/storage.yml
  roles:
  - getCredentials
  - configureOSG
  - configureSC
