#
# Deploy
#

- hosts: clusters
- hosts: fe

- hosts:
  - fe
  - cc
  - sc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - isNC: false
  roles:
  - vlanConfig

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - isNC: true
  roles:
  - vlanConfig
  - bridgeConfig

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - common
  - clc

- hosts: ufs
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - common
  - ufs

- hosts: walrus
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - common
  - walrus

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerUFS
  - registerWalrus

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - common
  - cc

- hosts: sc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - common
  - sc

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerCC
  - registerSC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - common
  - nc

- hosts: nc

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerNC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - startCompute
