#
# Deploy
#

- hosts: clusters
- hosts: fe

- hosts:
  - fe
  - clusters
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - networkConfig

# - hosts: clc
#   vars_files:
#   - vars/main.yml
#   - vars/networking.yml
#   roles:
#   - common
#   - clc

# - hosts: ufs
#   vars_files:
#   - vars/main.yml
#   - vars/networking.yml
#   roles:
#   - common
#   - ufs

# - hosts: walrus
#   vars_files:
#   - vars/main.yml
#   - vars/networking.yml
#   roles:
#   - common
#   - walrus

# - hosts: clc
#   vars_files:
#   - vars/main.yml
#   roles:
#   - registerUFS
#   - registerWalrus

# - hosts: cc
#   vars_files:
#   - vars/main.yml
#   - vars/networking.yml
#   roles:
#   - common
#   - cc

# - hosts: storage
#   vars_files:
#   - vars/main.yml
#   roles:
#   - common
#   - sc

# - hosts: nodes
#   vars_files:
#   - vars/main.yml
#   roles:
#   - common
#   - nc

# - hosts: cluster
#   vars_files:
#   - vars/main.yml
#   roles:
#   - registerNC

# - hosts: nodes
#   vars_files:
#   - vars/main.yml
#   roles:
#   - startCompute
