#
# Deploy
#

- hosts: clusters
- hosts: java_fe

- hosts: all
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - setup

- hosts: all
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  roles:
  - common

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - clc

- hosts: ufs
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - ufs

- hosts: walrus
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - walrus

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerUFS
  - registerWalrus

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - cc

- hosts: sc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  - vars/java.yml
  vars:
  - java_iface: "{{ vlan_iface }}.{{ vlan_tag }}"
  roles:
  - sc

- hosts: clc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerCC
  - registerSC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - nc

- hosts: nc

- hosts: cc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - registerNC

- hosts: nc
  vars_files:
  - vars/main.yml
  - vars/networking.yml
  roles:
  - startCompute
