###########################################################
#
# This role can be called anytime to repeat creds download
#
#

- name: Wait for UFS 8773 to be networkly started
  wait_for: host="{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}" port=8773 state=started
  with_items:
  - "{{ groups.ufs }}"
  tags:
  - credentials
  - ufs_ready

- name: Wait for UFS to be UP and detected by CLC
  wait_for: search_regex="riakcs,ceph-rgw,walrus,s3" path="{{ eucalyptus_cloudoutput_path }}"
  tags:
  - credentials
  - ufs_ready

- name: Get the credentials ZIP file
  shell: rm -rfv "{{ euca_admin_zip_file }}" ; euca-get-credentials {{ euca_admin_zip_file }}
  tags:
  - credentials

- name: Unzip the credentials
  unarchive: copy=no src="{{ euca_admin_zip_file }}" dest="{{ euca_admin_creds_path }}" creates=yes
  tags:
  - credentials

- name: Check services
  shell: source "{{ euca_admin_creds_path }}"/eucarc ; euca-describe-services
  tags:
  - credentials
  - debug
  ignore_errors: yes
