#
# Create briges on NCs
#

- name: Check if bridge already exists [VLAN]:
  shell: brctl show | grep {{ nc_bridge_prefix }}{{ vlan_tag }} | wc -l
  register: bridge_exists
  when:
  - use_vlans

- name: Create bridge
  shell brctl addbr {{ nc_bridge_prefix }}{{ vlan_tag }}
  when:
  - bridge_exists == "0"

- name: Bridge to IFACE
  shell: brctl addif {{ nc_bridge_prefix }}{{ vlan_tag }} {{ vlan_iface }}.{{ vlan_tag }}
  when:
  - use_vlans
  - bridge_exists == "0"

- name: Flush IP address of bridge
  shell: ip addr flush {{ nc_bridge_prefix }}{{ vlan_tag }}
  when:
  - use_vlans
  - bridge_exists == "1"
  - flush_if_exists

- name: Set IP Address on the bridge
  shell: ip addr add {{ vlan_ip }} dev {{ nc_bridge_prefix }}{{ vlan_tag }}
  when:
  - flush_if_exists
  - use_vlans

- name: Enable Bridge IFACE
  shell: ipconfig {{ nc_bridge_prefix }}{{ vlan_tag }} up
