#
# Walrus Registration
#

- name: Debug Walrus IPs
  debug: msg="{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}" 
  with_items: "{{ groups.walrus }}"

- name: Register Walrus
  shell: euca_conf --register-service -T user-api -N {{ ufs_name }} -H "{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}" 
  with_items: "{{ groups.walrus }}"
