#
# Walrus Registration
#

- name: Register Walrus
  shell: euca_conf --register-walrus --partition walrus --host "{{ hostvars[item]['ansible_' + "%s.%d"|format(hostvars[item]['vlan_iface'], hostvars[item]['vlan_tag'])]['ipv4']['address'] }}" --component {{ hostvars[item]['walrus_name'] }}
  with_items: "{{ groups.walrus }}"
  ignore_errors: true
