#
# Cloud components
#

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - config
  - ufs
  - clc_keys

- name: Start UFS
  service: name=eucalyptus-cloud state=started
  tags:
  - run
  - ufs
