#
# Cloud components
#

- name: Setup cloud
  yum: name={{ item }} state=present
  with_items:
  - eucalyptus-cloud
  - eucalyptus-osg
  tags:
  - packages

- name: UFS Java binding
  template: src=eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
  tags:
  - init_config
  - ufs

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - config
  - ufs

