#
# All NCs common
#

- name: Setup NC packages
  yum: name=eucalyptus-nc state=present
  tags:
  - packages

- name: Setup eucanetd
  yum: name=eucanetd state=present
  when:
  - networking_mode == "EDGE"
  tags:
  - packages

- name: Set NC eucalyptus.conf
  template: src=eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
  tags:
  - init_config

- name: Authorize CC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/cc-' + hostvars[inventory_hostname]['partition'] + '.pem') }}"
  tags:
  - config

- name: Start libvirtd
  service: name=libvirtd state=started
  tags:
  - nc_cleanup

- name: Delete default libvirt network
  shell: virsh net-destroy default ; virsh net-undefine default
  ignore_errors: yes
  tags:
  - nc_cleanup

- name: Restart libvirtd
  service: name=libvirtd state=restarted
  tags:
  - nc_cleanup

