#
# All NCs common
#

- name: Setup NC packages
  yum: name=eucalyptus-nc state=present

- name: Setup eucanetd
  yum: name=eucanetd state=present
  when:
  - networking_mode == "EDGE"

- name: Apply all zeroconf in main network config file
  lineinfile: regexp=NOZEROCONF line=NOZEROCONF\=yes dest=/etc/sysconfig/network

- name: Reload network
  service: name=network state=restarted

- name: Update VNET Mode
  lineinfile: regexp=VNET_MODE line=VNET_MODE\=\"{{ networking_mode }}\" dest={{ euca_conf_path }}

- name: Metadata in private mode
  lineinfile: regexp=METADATA_USE_VM_PRIVATE line=METADATA_USE_VM_PRIVATE\=\"Y\" dest={{ euca_conf_path }}
  when: edge_using_private == True

- name: Update PRIV Interface
  lineinfile: regexp=VNET_PRIVINTERFACE line=VNET_PRIVINTERFACE\=\"{{ "%s%d"|format(nc_bridge_prefix, vlan_tag) }}\" dest={{ euca_conf_path }}
  when:
  - use_vlans
  - nc_use_bridges

- name: Update PRIV Interface
  lineinfile: regexp=VNET_PRIVINTERFACE line=VNET_PRIVINTERFACE\=\"{{ nc_private_iface }}\" dest={{ euca_conf_path }}
  when:
  - not use_vlans
  - not nc_use_bridges

- name: Update PUB Interface
  lineinfile: regexp=VNET_PUBINTERFACE line=VNET_PUBINTERFACE\=\"{{ nc_vnet_public }}\" dest={{ euca_conf_path }}

- name: Update BRIDGE Interface
  lineinfile: regexp=VNET_BRIDGE line=VNET_BRIDGE\=\"{{ "%s%d"|format(nc_bridge_prefix, vlan_tag) }}\" dest={{ euca_conf_path }}
  when:
  - use_vlans
  - nc_use_bridges

- name: Update BRIDGE Interface
  lineinfile: regexp=VNET_BRIDGE line=VNET_BRIDGE\=\"{{ nc_bridge_prefix }}\" dest={{ euca_conf_path }}
  when:
  - not use_vlans
  - nc_use_bridges

- name: Authorize CC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/cc-pub-key') }}"

- name: Start libvirtd
  service: name=libvirtd state=started

- name: Delete default libvirt network
  shell: virsh net-destroy default ; virsh net-undefine default
  ignore_errors: yes

- name: Restart libvirtd
  service: name=libvirtd state=restarted
