#
# Creates the VLAN on the defined iface
#

- name: Create the VLAN config file
  template: src=vlan.yml dest={{ netcfg_path }}/ifcfg-{{ nc_vlan_iface }}.{{ edge_vlan_tag }}

- name: Creates the bridge iface config file
  template: src=bridge.yml dest={{ netcfg_path }}/ifcfg-{{ nc_vlan_br_prefix }}{{ edge_vlan_tag }}

