#
# NC Registration
#

- name: Start CC service
  service: name=eucalyptus-cc state=started

- name: Register all NCs
  shell: euca_conf --register-nodes "{{ hostvars[item]['ansible_' + "%s%d"|format(nc_bridge_prefix, hostvars[item]['vlan_tag'])]['ipv4']['address'] }}"
  with_items: "{{ groups.nc }}"
  when: 
  - partition == "{{ hostvars[item]['partition'] }}"
  - nc_use_bridges
  - use_vlans
