
# All components common tasks
#

- name: Define vCPU overcommit
  shell: echo "{{ ansible_processor_vcpus }} * {{ cpu_overcommit }}" | bc
  register: nc_vcpu
  tags:
  - init_config
  - overcommit

- name: Set eucalyptus config
  template: src=eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
  tags:
  - init_config
