#
# Common CC stuff
#

- name: Setup CC package
  yum: name=eucalyptus-cc state=present

- name: Set VNET MODE
  lineinfile: regexp=VNET_MODE line=VNET_MODE\=\"{{ networking_mode }}\" dest={{ euca_conf_path }}

- name: "Configure EDGE"
  include: edge_conf.yml
  when: networking_mode == "EDGE"

- name: Generate ssh-key on CC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: cc_public_key

- name: Deploy CC ssh key
  authorized_key: user=root state=present key="{{ cc_public_key.ssh_public_key }}"

- name: Config CC ssh config
  copy: src=ssh_config dest=/root/.ssh/config

- name: Import CC public key
  fetch: src=/root/.ssh/id_rsa.pub dest=/var/tmp/cc-pub-key flat=yes

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
