#
# Walrus config
#

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - walrus
  - run
  - clc_keys

- name: Start Walrus
  service: name=eucalyptus-cloud state=started
  tags:
  - walrus
  - run
