#
# Walrus config
#

- name: Setup Walrus
  yum: name={{ item }} state=present
  with_items:
  - eucalyptus-walrus

- name: Debug
  debug: msg={{ hostvars[inventory_hostname]['ansible_' + java_iface] }}

- name: Walrus Java binding
  lineinfile: regexp=CLOUD_OPTS line=CLOUD_OPTS\=\"--bind-addr={{  hostvars[inventory_hostname]['ansible_' + java_iface]['ipv4']['address'] }}\" dest={{ euca_conf_path }}
